# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c730773719df2aa7ad6857bf8fe862186db6563e066300018bbc9fd2606802f6283f34a566909fce9a1e23e505734de6f0f87a7e1c4194ea23df0689b4a4b56b

test:
  secret_key_base: a3d9ec99c8c10fbe6e8c0289e9f643e0491b606bbb8653d547c9915981655822022d81cf5a60e4d2ceb5d039085812802e65c88c7f5f6d8f1837669da9a52625

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
