# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7112317575cba3a6a0e4f0349ddf1cadb20478c77f5fefac0381e71ff571ba1b5fe5b9db4e049ca0d73fe80a727e81e3f24b800b72708250da7f7d86986ee77

test:
  secret_key_base: d6c359e6c92543a95bedaa5af579897cf06ba9f2731497b771dee8135ced3ff3a6ff84388eac9a36098194b804ff95b716388aaf071cf26b3390be9fc33e01aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
